VidPlace/VidPlace/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace VidPlace.Models
{
    
        public class Customer
        {
        public int Id { get; set; }
        [Required][MaxLength(100)]
        public string Name { get; set; }
            public string Address { get; set; }
        public bool IsSubScribedtoNewsLetter { get; set; }
        public DateTime BirthDate { get; set; }
        public Membership MembershipType { get; set; }
        
        public byte MembershipId { get; set; }

        public override string ToString()
            {
                return "Customer Name: " + Name + ", Address: " + Address;
            }


     

    }

       
    }

VidPlace/VidPlace/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VidPlace.Models;
using System.Data.Entity;

namespace VidPlace.Controllers
{
    public class CustomersController : Controller
    {
        // GET: Customers

        private ApplicationDbContext _context;

        public CustomersController()
        {
            _context = new ApplicationDbContext();
        }

  

        public ActionResult Index()
        {
            var customers = _context.Customers.Include(c => c.MembershipType).ToList();

            return View(customers);
        }

       

        public ActionResult Details(int id)
        {
            var customer = _context.Customers.Include(c => c.MembershipType).SingleOrDefault(c => c.Id == id);
            if(customer == null)
            {
                return HttpNotFound();
            }
            
            return View(customer);
        }

    }
}

VidPlace/VidPlace/Views/Customers/Details.cshtml
@model VidPlace.Models.Customer
@{
    ViewBag.Title = "Customer Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<p>@Model.Name</p>
<p>@Model.MembershipType.MembershipName</p>
<p>@Model.BirthDate.ToShortDateString()</p>

VidPlace/VidPlace/Views/Customers/GetCustomer.cshtml
@model VidPlace.Models.Customer
@{
    ViewBag.Title = "GetCustomer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@Model.Name</h1>
<h2>@Model.Address</h2>
<h3>@Model.Id</h3>

VidPlace/VidPlace/Views/Customers/Index.cshtml
@model IEnumerable<VidPlace.Models.Customer>
    
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (!Model.Any())
{
    <p>There are no customers</p>
}
else
{   <ul>
    foreach (var c in Model)
    {
        <li>@Html.ActionLink(c.Name, "Detail", "Customers", new { id = c.Id }, null)</li>
    <li>c.BirthDate</li>
    }
    </ul>

}